title: Bee-Jay's Github Blog
author: Bee-Jay Warfield
email: bjwarfield83@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A github pages tutorial.

# social links
twitter_username: \@itsabeejay
github_username:  #bwarfield

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
